#!/data/data/com.termux/files/usr/bin/bash
set -e -u

SCRIPTNAME=termux-clipboard-set
show_usage () {
    echo "Usage: $SCRIPTNAME [text]"
    echo "Set the system clipboard text. The text to set is either supplied as arguments or read from stdin if no arguments are given."
    exit 0
}

while getopts :h option
do
    case "$option" in
	h) show_usage;;
	?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $(($OPTIND-1))

if [ $# = 0 ]; then
    text=$(</proc/$$/fd/0)
else
    echo "else if"
fi

echo $text
echo "{'api_method' : 'Clipboard',
       'set' : true,
       'text' : '${text}'}" | /data/data/com.termux/files/usr/libexec/termux-api
